- .travis.yml
**Description**
This PR automate firebase deployment instead of storybook
> build(travis): automate firebase deployment

- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
**Description**
This PR closes #21.
> feat(faucet): handle faucet amount dynamically

- src/assets/colors/colors.css
- src/components/access-keystore/index.tsx
- src/components/access-tabs/index.tsx
- src/components/access-tabs/style.css
- src/components/button/style.css
- src/components/footer/__snapshots__/spec.tsx.snap
- src/components/footer/index.tsx
- src/components/footer/style.css
- src/index.css
**Description**
This PR closes #24 and ensures all text elements have sufficient color contrast between the text
in the foreground and background color behind it.
https://dequeuniversity.com/rules/axe/3.1/color-contrast?application=lighthouse
https://www.w3.org/WAI/standards-guidelines/wcag
> refactor: provide sufficient contrast ratio

- src/components/account-info/index.tsx
- src/components/send-form/index.tsx
- src/redux/zil/sagas.ts
**Description**
This PR formats the address from `/^[a-fA-F0-9]{40}$/` to `/^0x[a-fA-F0-9]{40}$/`.
> fix: format address

- package.json
- src/components/account-info/index.tsx
- src/components/faucet-form/index.tsx
- src/components/send-form/index.tsx
- src/redux/zil/sagas.ts
- src/utils.ts
- yarn.lock
**Summary**
This PR adopts bech32 address format
https://github.com/Zilliqa/Zilliqa/wiki/Address-Standard#current-adoption
> feat: adopt bech32 address

- src/components/account-info/__snapshots__/test.tsx.snap
- src/components/account-info/index.tsx
This PR resolves https://github.com/Zilliqa/nucleus-wallet/issues/42
> feat: display ByStr20 address

- src/components/faucet-form/index.tsx
- src/containers/FaucetContainer.tsx
- src/contexts/zil-context/index.tsx
This PR resolves https://github.com/Zilliqa/nucleus-wallet/issues/45
> feat(faucet): make the faucet user flow concise

- .travis.yml
> build: use node 10

- package.json
- src/components/account-info/index.tsx
- src/components/faucet-request/index.tsx
- src/components/send-form/index.tsx
- src/containers/calculate/index.tsx
- src/use-async-fn.ts
- yarn.lock
> feat: drop react-fetcha

- src/use-async-fn.ts
This PR formats code so that it can pass CI
> style: format code

- src/containers/home/index.tsx
This PR changes the background color as the following:
> feat: background color

- README.md
This PR sets branch for travis ci badge as development branch which is the default branch.
The default branch is now development branch and it was master branch previously.
> docs: travis ci badge

- .travis.yml
- Dockerfile
- scripts/ci_script.sh
1. updated dockerfile minimise size
2. updated scripts/ci_script.sh to push static files to s3
3. updated .travis.yml to run ci_script.sh
> Firebase Migration to AWS

- src/components/faucet-request/index.tsx
- src/constants/index.ts
This PR uses the new reCAPTCHA site key and rename `CAPTCHA_SITE_KEY` -> `SITE_KEY`.
> refactor: site key

- src/components/account-info/__snapshots__/index.test.tsx.snap
- src/components/account-info/index.test.tsx
- src/components/account-info/index.tsx
- src/containers/send/index.tsx
- src/contexts/zil-context/index.tsx
This PR enables users to copy their public key.
https://user-images.githubusercontent.com/86328181/132592887-158524d7-d1d2-47e4-a2fc-f02e64e27c53.mov
> feat: copy public key

- public/config.json
- src/contexts/zil-context/index.tsx
- src/routes.tsx
This PR fixes #123 
config.json will be injected into the deployment post build.
> refactor: use config.json

- src/routes.tsx
This PR styles the loading text for fetching config.json.
> feat: style loading text

- public/config.json
This PR fixes chain id. The issue is from https://github.com/Zilliqa/nucleus-wallet/pull/125.
Since `config.json` will be injected into the deployment post build, the issue has impacted only local development.
> fix: chain id

- package.json
- yarn.lock
This PR uses zilliqa-js v3.3.0
> build: zilliqa-js v3.3.0

- src/components/account-info/index.test.tsx
- src/components/account-info/index.tsx
- src/components/faucet-request/index.tsx
- src/components/send-form/index.tsx
- src/use-async-fn.test.tsx
- src/use-async-fn.ts
This PR improves `UseAsyncFn()` and adds tests.
> feat: use-async-fn

- README.md
- scripts/ci_deploy.sh
- src/components/account-info/index.test.tsx
- src/components/footer/__snapshots__/index.test.tsx.snap
- src/components/footer/index.tsx
- src/components/header/index.test.tsx
This PR handles the new repo name `dev-wallet`
> feat: new repo name

- package.json
- yarn.lock
This PR uses zilliqa-js v3.3.4
> build: zilliqa-js v3.3.4

- src/contexts/zil-context/index.tsx
This PR uses testnet as default network.
> feat: defaults to testnet

- package.json
- src/contexts/zil-context/index.tsx
- yarn.lock
This PR merges the changes to master
> master <- dev 
